'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { Eye,ImagePlus,Pencil,Trash2,X } from 'lucide-react';
import AdminShell from '@/components/admin/AdminShell';
import { createClient } from '@/lib/supabase/client';
type Winery={id:string;name:string;slug:string;logo_url:string|null;enabled:boolean;featured:boolean;sort_order:number;products?:{count:number}[]};
export default function Wineries(){const s=createClient();const [items,setItems]=useState<Winery[]>([]);const [edit,setEdit]=useState<any|null>(null);const [busy,setBusy]=useState(false);async function load(){const {data,error}=await s.from('wineries').select('*,products(count)').order('name');if(error)return alert(error.message);setItems((data||[]) as Winery[])}useEffect(()=>{load()},[]);
 async function upload(file:File){const ext=file.name.split('.').pop()||'png';const path=`logos/${Date.now()}.${ext}`;const {error}=await s.storage.from('wineries').upload(path,file);if(error)return alert(error.message);const {data}=s.storage.from('wineries').getPublicUrl(path);setEdit((e:any)=>({...e,logo_url:data.publicUrl}))}
 async function save(){if(!edit?.name)return;setBusy(true);const slug=(edit.slug||edit.name).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const payload={name:edit.name,slug,logo_url:edit.logo_url||null,enabled:!!edit.enabled,featured:!!edit.featured,sort_order:Number(edit.sort_order)||0};const {error}=edit.id?await s.from('wineries').update(payload).eq('id',edit.id):await s.from('wineries').insert(payload);if(error)alert(error.message);else{setEdit(null);load()}setBusy(false)}
 async function remove(w:Winery){const count=w.products?.[0]?.count||0;if(count){alert(`No se puede eliminar: tiene ${count} productos asociados. Entrá a la bodega y reasigná esos productos primero.`);return}if(!confirm(`¿Eliminar ${w.name}?`))return;const {error}=await s.from('wineries').delete().eq('id',w.id);if(error)alert(error.message);else load()}
 return <AdminShell title="Bodegas" subtitle="Cada bodega corresponde al proveedor del listado del cliente. Entrá para ver y administrar sus productos asociados."><section className="admin-card"><div className="admin-card-head"><div><h2>Listado de bodegas</h2><p>{items.length} bodegas registradas.</p></div><button className="btn btn-primary" onClick={()=>setEdit({name:'',slug:'',logo_url:'',enabled:true,featured:false,sort_order:0})}>Nueva bodega</button></div><div className="winery-admin-grid">{items.map(w=>{const count=w.products?.[0]?.count||0;return <article key={w.id}><Link href={`/admin/bodegas/${w.id}`} className="winery-card-main"><div className="winery-admin-logo">{w.logo_url?<img src={w.logo_url} alt={w.name}/>:<span className="winery-logo-empty">{w.name.slice(0,2).toUpperCase()}</span>}</div><h3>{w.name}</h3><p>{count} productos asociados</p><p>{w.enabled?'Visible en el sitio':'Deshabilitada'} {w.featured?'· Destacada':''}</p></Link><div className="row-actions"><Link href={`/admin/bodegas/${w.id}`}><Eye size={15}/> Ver productos</Link><button onClick={()=>setEdit({...w})}><Pencil size={15}/> Editar</button><button onClick={()=>remove(w)}><Trash2 size={15}/> Eliminar</button></div></article>})}</div></section>{edit&&<div className="admin-modal-backdrop"><section className="admin-modal compact"><button className="admin-modal-close" onClick={()=>setEdit(null)}><X/></button><h2>{edit.id?'Editar bodega':'Nueva bodega'}</h2><div className="admin-form-grid"><label className="wide">Nombre<input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label className="wide upload-field"><span>Logo</span><div>{edit.logo_url?<img src={edit.logo_url} alt=""/>:<div className="admin-upload-empty"><ImagePlus size={26}/><span>Sin logo</span></div>}<label className="btn btn-secondary"><ImagePlus size={15}/>Subir logo<input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></div></label><label>Orden<input type="number" value={edit.sort_order||0} onChange={e=>setEdit({...edit,sort_order:e.target.value})}/></label><label className="check-row"><input type="checkbox" checked={!!edit.enabled} onChange={e=>setEdit({...edit,enabled:e.target.checked})}/> Visible</label><label className="check-row"><input type="checkbox" checked={!!edit.featured} onChange={e=>setEdit({...edit,featured:e.target.checked})}/> Destacada</label></div><button className="btn btn-primary admin-save" disabled={busy} onClick={save}>{busy?'Guardando...':'Guardar'}</button></section></div>}</AdminShell>}
