import { NextResponse } from 'next/server';
import { PDFDocument,StandardFonts,rgb } from 'pdf-lib';
import { createAdminClient } from '@/lib/supabase/admin';
import { requireAdmin } from '@/lib/supabase/server';

export const runtime='nodejs';
export async function POST(){if(!await requireAdmin())return NextResponse.json({error:'No autorizado.'},{status:401});try{const s=createAdminClient();const {data:products,error}=await s.from('products').select('name,article_name,price,units_per_box,categories(name),wineries(name),varietals(name)').eq('enabled',true).order('name');if(error)throw error;const pdf=await PDFDocument.create();const regular=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);const W=595,H=842,margin=42;let page=pdf.addPage([W,H]);let y=H-margin;
 const header=()=>{page.drawText('DOLCE VINO - CATALOGO ACTUALIZADO',{x:margin,y:y-10,size:17,font:bold,color:rgb(.12,.13,.09)});y-=36;page.drawText(`Actualizado: ${new Date().toLocaleDateString('es-AR')}`,{x:margin,y,size:9,font:regular,color:rgb(.35,.36,.32)});y-=22;page.drawLine({start:{x:margin,y},end:{x:W-margin,y},thickness:1,color:rgb(.75,.8,.08)});y-=18};header();
 for(const p of products||[]){if(y<70){page=pdf.addPage([W,H]);y=H-margin;header()}const winery=(p as any).wineries?.name||'';const varietal=(p as any).varietals?.name||'';const category=(p as any).categories?.name||'';const name=String(p.name).slice(0,52);const article=String((p as any).article_name||'').slice(0,78);page.drawText(name,{x:margin,y,size:10,font:bold,color:rgb(.08,.08,.07)});page.drawText(article||[winery,varietal,category].filter(Boolean).join(' - ').slice(0,75),{x:margin,y:y-13,size:8,font:regular,color:rgb(.38,.39,.35)});page.drawText(`$ ${Number(p.price).toLocaleString('es-AR')}  |  Caja x${p.units_per_box}`,{x:370,y:y-2,size:8,font:bold,color:rgb(.12,.13,.09)});y-=34;}
 const bytes=await pdf.save();const path='catalogos/catalogo-automatico.pdf';const {error:up}=await s.storage.from('site').upload(path,Buffer.from(bytes),{contentType:'application/pdf',upsert:true});if(up)throw up;const {data:urlData}=s.storage.from('site').getPublicUrl(path);const url=`${urlData.publicUrl}?v=${Date.now()}`;await s.from('site_settings').upsert({key:'generated_catalog_pdf',value:{url,generated_at:new Date().toISOString(),products:(products||[]).length}});return NextResponse.json({url,products:(products||[]).length});}catch(e:any){return NextResponse.json({error:e.message||'Error generando PDF'},{status:500})}}
