'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { ArrowLeft,Pencil } from 'lucide-react';
import AdminShell from '@/components/admin/AdminShell';
import { createClient } from '@/lib/supabase/client';

type Product={id:string;name:string;article_name:string|null;price:number;enabled:boolean;units_per_box:number;image_url:string|null;varietals?:any;categories?:any};
export default function WineryProducts({params}:{params:{id:string}}){const s=createClient();const [name,setName]=useState('Bodega');const [items,setItems]=useState<Product[]>([]);const [loading,setLoading]=useState(true);async function load(){const [{data:w},{data:p,error}]=await Promise.all([s.from('wineries').select('name').eq('id',params.id).single(),s.from('products').select('id,name,article_name,price,enabled,units_per_box,image_url,varietals(name),categories(name)').eq('winery_id',params.id).order('name')]);if(error)alert(error.message);setName(w?.name||'Bodega');setItems((p||[]) as unknown as Product[]);setLoading(false)}useEffect(()=>{load()},[params.id]);return <AdminShell title={name} subtitle="Productos asociados a esta bodega/proveedor."><section className="admin-card"><div className="admin-card-head"><div><Link href="/admin/bodegas" className="admin-back-link"><ArrowLeft size={15}/> Volver a bodegas</Link><h2>Productos asociados</h2><p>{loading?'Cargando...':`${items.length} productos encontrados.`}</p></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Imagen</th><th>Marca / producto</th><th>Categoría</th><th>Varietal</th><th>Precio</th><th>Caja</th><th>Estado</th><th></th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td>{p.image_url?<img className="admin-product-thumb" src={p.image_url} alt=""/>:<div className="admin-image-empty">Sin imagen</div>}</td><td><strong>{p.name}</strong><small>{p.article_name||'Sin detalle'}</small></td><td>{(Array.isArray(p.categories)?p.categories[0]?.name:p.categories?.name)||'-'}</td><td>{(Array.isArray(p.varietals)?p.varietals[0]?.name:p.varietals?.name)||'-'}</td><td>$ {Number(p.price).toLocaleString('es-AR',{maximumFractionDigits:2})}</td><td>x{p.units_per_box}</td><td><span className={p.enabled?'status-pill is-on':'status-pill'}>{p.enabled?'Visible':'Oculto'}</span></td><td><Link className="table-edit-link" href={`/admin/vinos?editar=${p.id}`}><Pencil size={14}/> Editar</Link></td></tr>)}</tbody></table></div>{!loading&&!items.length&&<div className="admin-empty-state">Esta bodega todavía no tiene productos asociados. Podés asignarla desde Gestión de vinos.</div>}</section></AdminShell>}
