'use client';
import { useEffect,useState } from 'react';
import { FileDown,RefreshCw,Upload } from 'lucide-react';
import AdminShell from '@/components/admin/AdminShell';
import { createClient } from '@/lib/supabase/client';
export default function CatalogAdmin(){const s=createClient();const [manual,setManual]=useState('');const [generated,setGenerated]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');async function load(){const {data}=await s.from('site_settings').select('*').in('key',['catalog_pdf','generated_catalog_pdf']);for(const row of data||[]){if(row.key==='catalog_pdf')setManual(row.value?.url||'');if(row.key==='generated_catalog_pdf')setGenerated(row.value?.url||'')}}useEffect(()=>{load()},[]);
 async function upload(file:File){setBusy(true);const path=`catalogos/catalogo-manual-${Date.now()}.pdf`;const {error}=await s.storage.from('site').upload(path,file,{contentType:'application/pdf'});if(error){alert(error.message);setBusy(false);return}const {data}=s.storage.from('site').getPublicUrl(path);await s.from('site_settings').upsert({key:'catalog_pdf',value:{url:data.publicUrl,uploaded_at:new Date().toISOString()}});setManual(data.publicUrl);setMessage('Catálogo manual actualizado.');setBusy(false)}
 async function generate(){setBusy(true);setMessage('Generando catálogo automático...');const res=await fetch('/api/catalog/generate',{method:'POST'});const body=await res.json();if(!res.ok)alert(body.error||'No se pudo generar');else{setGenerated(body.url);setMessage(`Catálogo automático actualizado con ${body.products} productos.`)}setBusy(false)}
 return <AdminShell title="Catálogo PDF" subtitle="Podés subir un PDF propio y también regenerar el catálogo automático basado en los productos visibles."><section className="admin-card"><div className="admin-card-head"><div><h2>Catálogo subido</h2><p>Este archivo puede utilizarse como catálogo principal cuando el cliente tenga un diseño editorial propio.</p></div><label className="btn btn-primary"><Upload size={16}/> Subir PDF<input hidden type="file" accept="application/pdf" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></div>{manual?<a className="catalog-file-link" href={manual} target="_blank"><FileDown/>Ver catálogo cargado</a>:<p className="empty-admin-state">Todavía no se cargó un PDF manual.</p>}</section><section className="admin-card"><div className="admin-card-head"><div><h2>Catálogo automático</h2><p>Se regenera al editar precios, stock, disponibilidad, cajas o productos. También podés forzarlo desde aquí.</p></div><button className="btn btn-primary" disabled={busy} onClick={generate}><RefreshCw size={16}/> Regenerar ahora</button></div>{generated?<a className="catalog-file-link" href={generated} target="_blank"><FileDown/>Abrir catálogo automático</a>:<p className="empty-admin-state">Aún no se generó el catálogo automático.</p>}</section>{message&&<div className="admin-message">{message}</div>}</AdminShell>}
