'use client';
import { useEffect,useState } from 'react';
import { ImagePlus } from 'lucide-react';
import AdminShell from '@/components/admin/AdminShell';
import { createClient } from '@/lib/supabase/client';
type Banner={id?:string;type:'hero'|'middle';title:string;subtitle:string;desktop_image_url:string;mobile_image_url:string;enabled:boolean;sort_order:number};
const initial:Banner[]=[0,1,2].map(i=>({type:'hero',title:'',subtitle:'',desktop_image_url:'',mobile_image_url:'',enabled:true,sort_order:i}));
export default function Banners(){const s=createClient();const [hero,setHero]=useState<Banner[]>(initial);const [middle,setMiddle]=useState<Banner>({type:'middle',title:'',subtitle:'',desktop_image_url:'',mobile_image_url:'',enabled:true,sort_order:0});const [message,setMessage]=useState('');useEffect(()=>{(async()=>{const {data}=await s.from('site_banners').select('*').in('type',['hero','middle']).order('sort_order');const hs=(data||[]).filter((x:any)=>x.type==='hero');if(hs.length)setHero([0,1,2].map(i=>hs[i]||initial[i]));const m=(data||[]).find((x:any)=>x.type==='middle');if(m)setMiddle(m)})()},[]);
 async function upload(file:File,target:'hero'|'middle',index:number,mode:'desktop'|'mobile'){const ext=file.name.split('.').pop()||'png';const path=`banners/${target}-${index}-${mode}-${Date.now()}.${ext}`;const {error}=await s.storage.from('site').upload(path,file);if(error)return alert(error.message);const {data}=s.storage.from('site').getPublicUrl(path);const key=mode==='desktop'?'desktop_image_url':'mobile_image_url';if(target==='hero')setHero(v=>v.map((b,i)=>i===index?{...b,[key]:data.publicUrl}:b));else setMiddle(v=>({...v,[key]:data.publicUrl}))}
 async function upsertBanner(b:Banner){const payload={type:b.type,title:b.title||null,subtitle:b.subtitle||null,desktop_image_url:b.desktop_image_url||null,mobile_image_url:b.mobile_image_url||null,enabled:b.enabled,sort_order:b.sort_order};if(b.id)return s.from('site_banners').update(payload).eq('id',b.id);const res=await s.from('site_banners').insert(payload).select().single();if(res.data)b.id=res.data.id;return res}
 async function save(){for(const b of hero)await upsertBanner(b);await upsertBanner(middle);setMessage('Banners guardados correctamente.')}
 const Card=({b,index,target,onChange}:{b:Banner;index:number;target:'hero'|'middle';onChange:(b:Banner)=>void})=><article className="banner-admin-card"><div className="banner-preview">{b.desktop_image_url?<img src={b.desktop_image_url} alt=""/>:<div className="banner-empty-preview">Sin imagen</div>}</div><h3>{target==='hero'?`Hero ${index+1}`:'Banner del medio'}</h3><p>
  <strong>Desktop:</strong> {target==='hero'?'1920 × 820 px':'1920 × 410 px'}<br/>
  <strong>Mobile:</strong> {target==='hero'?'1080 × 1500 px':'1080 × 750 px'}
</p><label>Título<input value={b.title||''} onChange={e=>onChange({...b,title:e.target.value})}/></label><label>Subtítulo<input value={b.subtitle||''} onChange={e=>onChange({...b,subtitle:e.target.value})}/></label><div className="banner-upload-row"><label className="btn btn-secondary"><ImagePlus size={14}/>Imagen desktop<input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],target,index,'desktop')}/></label><label className="btn btn-secondary"><ImagePlus size={14}/>Imagen mobile<input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],target,index,'mobile')}/></label></div><label className="check-row"><input type="checkbox" checked={b.enabled} onChange={e=>onChange({...b,enabled:e.target.checked})}/> Activo</label></article>;
 return <AdminShell title="Banners" subtitle="Administrá las tres imágenes del hero y el banner central. Las imágenes mobile se usan automáticamente en pantallas pequeñas."><section className="admin-card"><div className="admin-card-head"><div><h2>Hero principal</h2><p>Tres banners rotativos. Tamaño recomendado: 1920 × 820 px desktop y 1080 × 1500 px mobile.</p></div></div><div className="banner-admin-grid">{hero.map((b,i)=><Card key={i} b={b} index={i} target="hero" onChange={n=>setHero(v=>v.map((x,j)=>j===i?n:x))}/>)}</div></section><section className="admin-card"><div className="admin-card-head"><div><h2>Banner del medio</h2><p>Se muestra entre destacados y productos generales. Usa las mismas medidas.</p></div></div><div className="banner-admin-grid one"><Card b={middle} index={0} target="middle" onChange={setMiddle}/></div></section>{message&&<div className="admin-message">{message}</div>}<button className="btn btn-primary admin-save-page" onClick={save}>Guardar banners</button></AdminShell>}
